import type { EndpointDef } from "@/lib/octo-endpoints";

export interface TentacleDef {
  id: string;
  glyph: string;
  name: string;
  title: string;
  model: string;
  role: string;
  size: string;
  category: "чат" | "анализ" | "медиа" | "документы" | "код" | "данные";
  installed: boolean;
  /** основной бэкенд щупальца */
  backend: "router" | "tentacles";
  /** инструменты, которые щупальце публикует голове */
  tools: string[];
  /** точки коннекта: UI уже знает куда стучаться */
  endpoints: EndpointDef[];
  /** форма входных данных (заготовка под наполнение) */
  input: Record<string, string>;
  /** форма ответа */
  output: Record<string, string>;
  /** требования к рабочему окну */
  ui: string[];
  hotkey?: string;
}

export const TENTACLE_CATEGORIES = [
  "все",
  "чат",
  "анализ",
  "медиа",
  "документы",
  "код",
  "данные",
] as const;
export type TentacleCategory = (typeof TENTACLE_CATEGORIES)[number];

export const TENTACLES: TentacleDef[] = [
  {
    id: "octo-chat",
    glyph: "💬",
    name: "octo-chat",
    title: "главный чат",
    model: "qwen3.8:27b · router",
    role: "свободный диалог, RAG по 455 чанкам lancedb, tools (bash sandbox, file r/w)",
    size: "—",
    category: "чат",
    installed: true,
    backend: "router",
    tools: ["bash_sandbox", "file_read", "file_write", "rag_search"],
    endpoints: [
      {
        method: "POST",
        path: "/v1/chat/completions",
        backend: "router",
        note: "чат · streaming SSE",
        stream: true,
      },
    ],
    input: {
      messages: "[{role, content}]",
      max_tokens: "number",
      temperature: "number",
      tools_enabled: "bool",
      rag_enabled: "bool",
    },
    output: {
      choices: "[{message:{role,content}}]",
      usage: "{prompt_tokens, completion_tokens}",
    },
    ui: [
      "центральное окно 50% экрана",
      "history с цветом по role",
      "markdown + code blocks",
      "auto-scroll",
      "streaming SSE",
      "cancel во время генерации",
    ],
    hotkey: "⌘K",
  },
  {
    id: "extraction",
    glyph: "🔬",
    name: "extraction",
    title: "извлечение из бинарников",
    model: "binwalk + cve match",
    role: "анализ .bin/.img/.hex, поиск прошивок, CVE matching",
    size: "0.4 ГБ",
    category: "анализ",
    installed: true,
    backend: "tentacles",
    tools: ["binwalk", "cveSearch", "firmwareParse", "bootloaderDetect"],
    endpoints: [
      { method: "POST", path: "/api/extraction/analyze", backend: "tentacles", note: "анализ файла", stream: true },
    ],
    input: { file: "<upload|b64>", type: "auto|firmware|bootloader", cve_db: "offline|nvd" },
    output: {
      findings: "[{offset,type,description}]",
      cves: "[{id,severity,description}]",
      summary: "string",
    },
    ui: [
      "drag-and-drop зона файла",
      "hex preview с подсветкой",
      "таблица CVE (id/severity/fix)",
      "сохранить в memory",
      "прогресс-бар",
    ],
  },
  {
    id: "diagnostics",
    glyph: "🔌",
    name: "diagnostics",
    title: "схемотехник",
    model: "qwen3.8:27b + vision projector",
    role: "диагностика электросхем, анализ изображений, расчёты, каталог, FMDB",
    size: "8.2 ГБ",
    category: "анализ",
    installed: true,
    backend: "tentacles",
    tools: [
      "circuitDiagnose",
      "circuitAnalyzeImage",
      "circuitCalculate",
      "circuitListComponents",
      "circuitGenerateSchematic",
      "circuitSearchFailures",
      "circuitAddFailure",
    ],
    endpoints: [
      { method: "POST", path: "/api/diagnostics/diagnose", backend: "tentacles", note: "диагноз по симптому" },
      { method: "POST", path: "/api/diagnostics/analyze_image", backend: "tentacles", note: "vision по схеме" },
      { method: "POST", path: "/api/diagnostics/calculate", backend: "tentacles", note: "R/C/L/мощность" },
      { method: "GET", path: "/api/diagnostics/components", backend: "tentacles", note: "каталог ~25 + LLM fallback" },
      { method: "POST", path: "/api/diagnostics/schematic", backend: "tentacles", note: "DSL → PNG" },
      { method: "GET", path: "/api/diagnostics/failures", backend: "tentacles", note: "FMDB · 45 режимов" },
    ],
    input: { symptom: "string", measurements: "{voltage,current,...}", use_big_model: "bool" },
    output: { diagnosis: "string", confidence: "0-1", references: "[component_ids]", steps: "[...]" },
    ui: [
      "2 колонки: вход / диагноз",
      "image upload → analyze (vision)",
      "калькулятор — отдельная вкладка",
      "каталог компонентов с поиском",
      "schematic generator (DSL → PNG)",
      "FMDB search",
    ],
  },
  {
    id: "persona",
    glyph: "🎭",
    name: "persona",
    title: "копирование личности",
    model: "qwen3.8:27b",
    role: "импорт переписок → профиль личности → brief / email draft",
    size: "—",
    category: "данные",
    installed: true,
    backend: "tentacles",
    tools: ["personaAnalyz", "personaBatch", "personaEmailDraft", "personaBrief"],
    endpoints: [
      { method: "POST", path: "/api/persona/analyze", backend: "tentacles", note: "профиль по выгрузке", stream: true },
      { method: "POST", path: "/api/persona/batch", backend: "tentacles", note: "пакетный разбор" },
      { method: "POST", path: "/api/persona/email_draft", backend: "tentacles", note: "черновик письма" },
      { method: "POST", path: "/api/persona/brief", backend: "tentacles", note: "brief по личности" },
    ],
    input: { name: "string", source: "tg|whatsapp|email|file", model: "string?" },
    output: {
      profile: "{big_five, style, triggers, pleases}",
      lexical_fingerprint: "{...}",
    },
    ui: [
      "drag-drop импорт chat export",
      "прогресс «анализирую…»",
      "профиль карточками (Big Five bars, triggers chips)",
      "кнопки brief / email",
      "история анализов в сайдбаре",
    ],
  },
  {
    id: "memory",
    glyph: "🧠",
    name: "memory",
    title: "память",
    model: "bge embeddings · lancedb",
    role: "semantic search по прошлым сессиям, recent conversations",
    size: "0.3 ГБ",
    category: "данные",
    installed: true,
    backend: "tentacles",
    tools: ["memorySearch", "memorySessions", "memoryRecent"],
    endpoints: [
      { method: "GET", path: "/api/memory/search?q=&k=10", backend: "tentacles", note: "semantic search" },
      { method: "GET", path: "/api/memory/sessions", backend: "tentacles", note: "список сессий" },
      { method: "GET", path: "/api/memory/recent", backend: "tentacles", note: "недавнее" },
    ],
    input: { q: "string", k: "10" },
    output: { results: "[{id,ts,cmd,response,score,domain}]", sessions: "[...]" },
    ui: [
      "поиск с автодополнением",
      "вкладки Search / Recent / Sessions",
      "карточки (snippet + дата + score)",
      "click → открыть сессию в чате",
    ],
    hotkey: "⌘M",
  },
  {
    id: "lovable",
    glyph: "🌐",
    name: "lovable",
    title: "генерация сайтов",
    model: "qwen3.8:27b",
    role: "Vite + React + TS + Tailwind проект из промпта",
    size: "—",
    category: "код",
    installed: true,
    backend: "tentacles",
    tools: ["webgenCreate"],
    endpoints: [
      { method: "POST", path: "/api/webgen/create", backend: "tentacles", note: "создать проект", stream: true },
    ],
    input: { prompt: "string", theme: "hud-oliva|grava…|cyber-mael", stack: "vite|next" },
    output: { project_path: "string", files: "[{path,content}]", preview_url: "string?" },
    ui: [
      "prompt textarea",
      "theme picker (7 тем с preview)",
      "file tree + открыть в VSCode",
      "streaming: файлы добавляются в дерево",
    ],
  },
  {
    id: "webgen-edit",
    glyph: "📝",
    name: "webgen-edit",
    title: "веб-редактор (surgical edit)",
    model: "qwen3.8:27b",
    role: "AI surgical edit файлов, git status, deploy patch",
    size: "—",
    category: "код",
    installed: true,
    backend: "tentacles",
    tools: ["webgenEditAi", "webgenDeployPatch", "webgenRemoteSnapshot", "webgenGit"],
    endpoints: [
      { method: "POST", path: "/webgen/edit/ai", backend: "tentacles", note: "surgical edit", stream: true },
      { method: "POST", path: "/webgen/edit/deploy_patch", backend: "tentacles", note: "применить патч" },
      { method: "POST", path: "/webgen/edit/remote_snapshot", backend: "tentacles", note: "снимок удалённого" },
      { method: "POST", path: "/webgen/edit/git", backend: "tentacles", note: "git status/commit" },
    ],
    input: {
      prompt: "string",
      target_file: "string",
      file_content: "string",
      model_config: "{...}",
      selected_element: "string?",
      folder: "string?",
      auto_apply: "bool?",
    },
    output: { patch: "unified diff", applied: "bool", status: "ok|conflict|error" },
    ui: [
      "file tree слева",
      "code editor справа",
      "AI prompt внизу",
      "diff view before/after",
      "git status panel",
    ],
  },
  {
    id: "presentation-edit",
    glyph: "📽",
    name: "presentation-edit",
    title: "презентации",
    model: "qwen3.8:27b",
    role: "Slidev (HTML+PDF) / Marp из markdown, 7 тем + fun-themes",
    size: "—",
    category: "документы",
    installed: true,
    backend: "tentacles",
    tools: ["slidevGenerate", "marpRender", "themeExtract", "slidevPilot"],
    endpoints: [
      { method: "POST", path: "/api/presentation/generate", backend: "tentacles", note: "slidev/marp", stream: true },
      { method: "POST", path: "/api/presentation/theme_extract", backend: "tentacles", note: "PDF → theme" },
    ],
    input: { prompt: "string", model: "string", theme: "string?", fun_theme: "string?", output: "html|pdf|pptx" },
    output: { slides: "[{layout,content,theme}]", file_path: "string" },
    ui: [
      "markdown editor слева",
      "slide preview справа (1 / all / thumbnails)",
      "theme picker + fun-theme",
      "экспорт HTML / PDF / PPTX",
      "streaming при генерации",
    ],
  },
  {
    id: "officecli",
    glyph: "📑",
    name: "officecli",
    title: "office documents",
    model: "officecli subprocess :26315",
    role: ".pptx/.docx/.xlsx — морфы, анимации, 3D, equations, live preview",
    size: "—",
    category: "документы",
    installed: false,
    backend: "tentacles",
    tools: [
      "officeCreate",
      "officeEdit",
      "officeMorph",
      "officeAnimation",
      "office3D",
      "officeEquation",
    ],
    endpoints: [
      { method: "POST", path: "/api/office/create", backend: "tentacles", note: "создать документ" },
      { method: "POST", path: "/api/office/edit", backend: "tentacles", note: "правка" },
      { method: "POST", path: "/api/office/morph", backend: "tentacles", note: "ShapeMorph keyframes" },
      { method: "POST", path: "/api/office/equation", backend: "tentacles", note: "LaTeX → render" },
    ],
    input: { type: "pptx|docx|xlsx", title: "string", slides: "[...]?", theme: "string?" },
    output: { file_path: "string", size_kb: "number", preview_url: "string" },
    ui: [
      "type picker (pptx/docx/xlsx)",
      "WYSIWYG preview",
      "morph timeline (start → end)",
      "equation editor (LaTeX)",
      "live preview pane",
    ],
  },
  {
    id: "media",
    glyph: "🖼",
    name: "media",
    title: "генерация медиа (cloud)",
    model: "flux-2 / veo-3 / lyria-3 · fallback qwen3.8",
    role: "image · video · music, cloud по умолчанию, fallback на local ollama",
    size: "—",
    category: "медиа",
    installed: true,
    backend: "tentacles",
    tools: [
      "mediaImage",
      "mediaVideo",
      "mediaMusic",
      "mediaStatus",
      "mediaListModels",
      "mediaDownloadModel",
    ],
    endpoints: [
      { method: "POST", path: "/api/media/generate", backend: "tentacles", note: "основной submit", stream: true },
      { method: "GET", path: "/api/media/status/<task_id>", backend: "tentacles", note: "polling 2s" },
      { method: "POST", path: "/api/media/cancel/<task_id>", backend: "tentacles", note: "отмена" },
      { method: "GET", path: "/api/media/list?type=", backend: "tentacles", note: "история генераций" },
      { method: "POST", path: "/api/media/download", backend: "tentacles", note: "скачать по URL" },
      { method: "GET", path: "/api/media/models", backend: "tentacles", note: "модели + цены" },
      { method: "GET", path: "/api/media/quota", backend: "tentacles", note: "остаток квоты" },
    ],
    input: {
      type: "image|video|music",
      prompt: "string",
      model: "flux-2|gpt-image-2|ideogram-4|recraft|veo-3|kling|lyria-3|suno-v4",
      size: "1024x1024|1280x720|…",
      aspect_ratio: "1:1|16:9|9:16|4:3|3:2",
      count: "1-4",
      seed: "number?",
    },
    output: {
      images: "[{url,path,size_kb,seed}]",
      task_id: "tsk_… (video/music)",
      status: "queued|processing|done|error",
      cost_usd: "number",
    },
    ui: [
      "вкладки Image / Video / Music",
      "model picker с ☁️/🏠 и ценой",
      "size presets + aspect ratio",
      "count slider, transparent toggle, seed",
      "reference image upload + style strength",
      "video: duration, first/last frame, audio, watermark",
      "music: lyrics, instrumental, genre chips",
      "gallery с download / open in chat / save local",
      "cost counter USD за день",
      "polling 2s + cancel + error display",
    ],
  },
];

export const tentacleById = (id: string) => TENTACLES.find((t) => t.id === id) ?? null;
