import type { EndpointDef } from "@/lib/octo-endpoints";

export interface TentacleDef {
  id: string;
  glyph: string;
  name: string;
  title: string;
  model: string;
  role: string;
  size: string;
  category: "чат" | "анализ" | "медиа" | "документы" | "код" | "данные" | "система";
  installed: boolean;
  /** основной бэкенд щупальца */
  backend: "router" | "tentacles" | "proxy";
  /** цепочка деградации: primary упал → идём по списку */
  fallback?: string[];
  /** инструменты, которые щупальце публикует голове */
  tools: string[];
  /** точки коннекта: UI уже знает куда стучаться */
  endpoints: EndpointDef[];
  /** форма входных данных (заготовка под наполнение) */
  input: Record<string, string>;
  /** форма ответа */
  output: Record<string, string>;
  /** требования к рабочему окну */
  ui: string[];
  hotkey?: string;
}

export const TENTACLE_CATEGORIES = [
  "все",
  "чат",
  "анализ",
  "медиа",
  "документы",
  "код",
  "данные",
  "система",
] as const;
export type TentacleCategory = (typeof TENTACLE_CATEGORIES)[number];

export const TENTACLES: TentacleDef[] = [
  {
    id: "octo-chat",
    glyph: "💬",
    name: "octo-chat",
    title: "главный чат",
    model: "qwen3.8:27b · router",
    role: "свободный диалог, RAG по 455 чанкам lancedb, tools (bash sandbox, file r/w)",
    size: "—",
    category: "чат",
    installed: true,
    backend: "router",
    tools: ["bash_sandbox", "file_read", "file_write", "rag_search"],
    endpoints: [
      {
        method: "POST",
        path: "/v1/chat/completions",
        backend: "router",
        note: "чат · streaming SSE",
        stream: true,
      },
    ],
    input: {
      messages: "[{role, content}]",
      max_tokens: "number",
      temperature: "number",
      tools_enabled: "bool",
      rag_enabled: "bool",
    },
    output: {
      choices: "[{message:{role,content}}]",
      usage: "{prompt_tokens, completion_tokens}",
    },
    ui: [
      "центральное окно 50% экрана",
      "history с цветом по role",
      "markdown + code blocks",
      "auto-scroll",
      "streaming SSE",
      "cancel во время генерации",
    ],
    hotkey: "⌘K",
  },
  {
    id: "extraction",
    glyph: "🔬",
    name: "extraction",
    title: "извлечение из бинарников",
    model: "binwalk + cve match",
    role: "анализ .bin/.img/.hex, поиск прошивок, CVE matching",
    size: "0.4 ГБ",
    category: "анализ",
    installed: true,
    backend: "tentacles",
    tools: ["binwalk", "cveSearch", "firmwareParse", "bootloaderDetect"],
    endpoints: [
      { method: "POST", path: "/api/extraction/analyze", backend: "tentacles", note: "анализ файла", stream: true },
    ],
    input: { file: "<upload|b64>", type: "auto|firmware|bootloader", cve_db: "offline|nvd" },
    output: {
      findings: "[{offset,type,description}]",
      cves: "[{id,severity,description}]",
      summary: "string",
    },
    ui: [
      "drag-and-drop зона файла",
      "hex preview с подсветкой",
      "таблица CVE (id/severity/fix)",
      "сохранить в memory",
      "прогресс-бар",
    ],
  },
  {
    id: "diagnostics",
    glyph: "🔌",
    name: "diagnostics",
    title: "схемотехник",
    model: "qwen3.8:27b + vision projector",
    role: "диагностика электросхем, анализ изображений, расчёты, каталог, FMDB",
    size: "8.2 ГБ",
    category: "анализ",
    installed: true,
    backend: "tentacles",
    tools: [
      "circuitDiagnose",
      "circuitAnalyzeImage",
      "circuitCalculate",
      "circuitListComponents",
      "circuitGenerateSchematic",
      "circuitSearchFailures",
      "circuitAddFailure",
    ],
    endpoints: [
      { method: "POST", path: "/api/diagnostics/diagnose", backend: "tentacles", note: "диагноз по симптому" },
      { method: "POST", path: "/api/diagnostics/analyze_image", backend: "tentacles", note: "vision по схеме" },
      { method: "POST", path: "/api/diagnostics/calculate", backend: "tentacles", note: "R/C/L/мощность" },
      { method: "GET", path: "/api/diagnostics/components", backend: "tentacles", note: "каталог ~25 + LLM fallback" },
      { method: "POST", path: "/api/diagnostics/schematic", backend: "tentacles", note: "DSL → PNG" },
      { method: "GET", path: "/api/diagnostics/failures", backend: "tentacles", note: "FMDB · 45 режимов" },
    ],
    input: { symptom: "string", measurements: "{voltage,current,...}", use_big_model: "bool" },
    output: { diagnosis: "string", confidence: "0-1", references: "[component_ids]", steps: "[...]" },
    ui: [
      "2 колонки: вход / диагноз",
      "image upload → analyze (vision)",
      "калькулятор — отдельная вкладка",
      "каталог компонентов с поиском",
      "schematic generator (DSL → PNG)",
      "FMDB search",
    ],
  },
  {
    id: "persona",
    glyph: "🎭",
    name: "persona",
    title: "копирование личности",
    model: "qwen3.8:27b",
    role: "импорт переписок → профиль личности → brief / email draft",
    size: "—",
    category: "данные",
    installed: true,
    backend: "tentacles",
    tools: ["personaAnalyz", "personaBatch", "personaEmailDraft", "personaBrief"],
    endpoints: [
      { method: "POST", path: "/api/persona/analyze", backend: "tentacles", note: "профиль по выгрузке", stream: true },
      { method: "POST", path: "/api/persona/batch", backend: "tentacles", note: "пакетный разбор" },
      { method: "POST", path: "/api/persona/email_draft", backend: "tentacles", note: "черновик письма" },
      { method: "POST", path: "/api/persona/brief", backend: "tentacles", note: "brief по личности" },
    ],
    input: { name: "string", source: "tg|whatsapp|email|file", model: "string?" },
    output: {
      profile: "{big_five, style, triggers, pleases}",
      lexical_fingerprint: "{...}",
    },
    ui: [
      "drag-drop импорт chat export",
      "прогресс «анализирую…»",
      "профиль карточками (Big Five bars, triggers chips)",
      "кнопки brief / email",
      "история анализов в сайдбаре",
    ],
  },
  {
    id: "memory",
    glyph: "🧠",
    name: "memory",
    title: "память",
    model: "bge embeddings · lancedb",
    role: "semantic search по прошлым сессиям, recent conversations",
    size: "0.3 ГБ",
    category: "данные",
    installed: true,
    backend: "tentacles",
    tools: ["memorySearch", "memorySessions", "memoryRecent"],
    endpoints: [
      { method: "GET", path: "/api/memory/search?q=&k=10", backend: "tentacles", note: "semantic search" },
      { method: "GET", path: "/api/memory/sessions", backend: "tentacles", note: "список сессий" },
      { method: "GET", path: "/api/memory/recent", backend: "tentacles", note: "недавнее" },
    ],
    input: { q: "string", k: "10" },
    output: { results: "[{id,ts,cmd,response,score,domain}]", sessions: "[...]" },
    ui: [
      "поиск с автодополнением",
      "вкладки Search / Recent / Sessions",
      "карточки (snippet + дата + score)",
      "click → открыть сессию в чате",
    ],
    hotkey: "⌘M",
  },
  {
    id: "lovable",
    glyph: "🌐",
    name: "lovable",
    title: "веб-генератор (создание нового)",
    model: "qwen3.8:27b · vision для UI reference",
    role: "новый проект с нуля: SPA / сайт / лендинг, деплой на staging, sync с Lovable Cloud",
    size: "—",
    category: "код",
    installed: true,
    backend: "tentacles",
    fallback: ["proxy"],
    tools: [
      "lovable_create_project",
      "lovable_generate",
      "lovable_scaffold",
      "lovable_deploy",
      "lovable_export_bundle",
    ],
    endpoints: [
      { method: "POST", path: "/api/webgen/create", backend: "tentacles", note: "инициализация структуры" },
      { method: "POST", path: "/api/webgen/generate", backend: "tentacles", note: "генерация кода · SSE chunk", stream: true },
      { method: "POST", path: "/api/webgen/scaffold", backend: "tentacles", note: "компонент / страница / роут" },
      { method: "POST", path: "/api/webgen/deploy", backend: "tentacles", note: "GitHub push + авто-деплой" },
      { method: "POST", path: "/api/webgen/export_bundle", backend: "tentacles", note: "production build (dist/)" },
    ],
    input: {
      project_name: "my-elsa-site",
      framework: "react|vite|nextjs|vanilla",
      prompt: "string",
      style: "modern|minimal|cyberpunk",
      deploy_target: "github|netlify|vercel|vps",
      github_repo: "user/repo?",
    },
    output: {
      project_path: "string",
      files_created: "[string]",
      tokens_used: "number",
      deploy_url: "string?",
    },
    ui: [
      "prompt textarea + framework / style picker",
      "streaming: файлы появляются в дереве по chunk",
      "file tree + открыть в VSCode",
      "deploy target picker + ссылка на staging",
      "export bundle (dist/) кнопкой",
    ],
  },
  {
    id: "webgen-edit",
    glyph: "📝",
    name: "webgen-edit",
    title: "редактор существующего сайта",
    model: "qwen3.8:27b",
    role: "правка кода/контента существующего проекта: local или clone из GitHub, git, деплой, rollback",
    size: "—",
    category: "код",
    installed: true,
    backend: "tentacles",
    fallback: ["proxy"],
    tools: [
      "webgen_open_project",
      "webgen_edit_file",
      "webgen_refactor",
      "webgen_commit",
      "webgen_deploy",
      "webgen_preview",
      "webgen_rollback",
    ],
    endpoints: [
      { method: "POST", path: "/webgen/edit/open", backend: "tentacles", note: "открыть / clone проект" },
      { method: "POST", path: "/webgen/edit/file", backend: "tentacles", note: "точечная правка old→new" },
      { method: "POST", path: "/webgen/edit/refactor", backend: "tentacles", note: "AI-рефакторинг", stream: true },
      { method: "POST", path: "/webgen/edit/git", backend: "tentacles", note: "commit + push" },
      { method: "POST", path: "/webgen/edit/deploy", backend: "tentacles", note: "staging | prod" },
      { method: "POST", path: "/webgen/edit/preview", backend: "tentacles", note: "dev server в iframe" },
      { method: "POST", path: "/webgen/edit/rollback", backend: "tentacles", note: "откат коммита" },
    ],
    input: {
      project_path: "/Users/admin/workspace/…",
      file: "src/components/Hero.jsx",
      instruction: "string",
      old_text: "string?",
      new_text: "string?",
      branch: "main",
      commit_message: "string?",
    },
    output: {
      diff_preview: "unified diff",
      files_changed: "[string]",
      git_branch: "string",
      last_commit: "string",
      deploy_url: "string?",
    },
    ui: [
      "file tree слева",
      "code editor + live preview в iframe",
      "AI instruction внизу (refactor)",
      "diff view before/after",
      "git panel: branch · last commit · commit/push",
      "deploy staging/prod + rollback",
    ],
  },
  {
    id: "presentation-edit",
    glyph: "📽",
    name: "presentation-edit",
    title: "презентации и документы",
    model: "qwen3.6-8k · officecli :26315",
    role: "PPTX/DOCX/XLSX через OfficeCLI, генерация КП, live preview в HTML",
    size: "—",
    category: "документы",
    installed: true,
    backend: "tentacles",
    fallback: ["proxy"],
    tools: [
      "officecliCreate",
      "officecliAdd",
      "officecliSet",
      "officecliRemove",
      "officecliGet",
      "officecliViewHtml",
      "officecliViewScreenshot",
      "officecliMerge",
      "officecliBatch",
      "officecliWatch",
      "officecliPresentationBuild",
      "kpCreate",
      "kpList",
      "kpStatus",
    ],
    endpoints: [
      { method: "POST", path: "/api/presentation/create", backend: "tentacles", note: "blank pptx/docx/xlsx" },
      { method: "POST", path: "/api/presentation/slide", backend: "tentacles", note: "add / edit / remove слайд" },
      { method: "POST", path: "/api/presentation/style", backend: "tentacles", note: "bold/color/font/size" },
      { method: "POST", path: "/api/presentation/build", backend: "tentacles", note: "анимации · morph · 3D · charts", stream: true },
      { method: "GET", path: "/api/presentation/preview", backend: "tentacles", note: "HTML live preview :26315" },
      { method: "POST", path: "/api/presentation/export_pdf", backend: "tentacles", note: "экспорт PDF" },
      { method: "POST", path: "/api/kp/create", backend: "tentacles", note: "КП (DOCX)", stream: true },
      { method: "GET", path: "/api/kp/list", backend: "tentacles", note: "все КП со статусами" },
    ],
    input: {
      file: "/path/to/pres.pptx",
      spec: "{PresentationSpec}?",
      slide_index: "number?",
      text: "string?",
      style: "{bold,color,font,size}?",
      kp_params: "{our_company,client_name,service_description,price}?",
    },
    output: {
      file: "string",
      slides_count: "number",
      html_preview: "string",
      kp_status: "queued|done|error",
    },
    ui: [
      "слайд-лента слева (thumbnails, drag reorder)",
      "live HTML preview справа (watch :26315)",
      "инспектор стиля: bold / color / font / size",
      "вкладка КП: параметры → генерация DOCX + статусы",
      "экспорт PDF / screenshot страниц",
      "batch-операции одним пайплайном",
    ],
  },
  {
    id: "officecli",
    glyph: "📑",
    name: "officecli",
    title: "office documents",
    model: "officecli subprocess :26315",
    role: ".pptx/.docx/.xlsx — морфы, анимации, 3D, equations, live preview",
    size: "—",
    category: "документы",
    installed: false,
    backend: "tentacles",
    tools: [
      "officeCreate",
      "officeEdit",
      "officeMorph",
      "officeAnimation",
      "office3D",
      "officeEquation",
    ],
    endpoints: [
      { method: "POST", path: "/api/office/create", backend: "tentacles", note: "создать документ" },
      { method: "POST", path: "/api/office/edit", backend: "tentacles", note: "правка" },
      { method: "POST", path: "/api/office/morph", backend: "tentacles", note: "ShapeMorph keyframes" },
      { method: "POST", path: "/api/office/equation", backend: "tentacles", note: "LaTeX → render" },
    ],
    input: { type: "pptx|docx|xlsx", title: "string", slides: "[...]?", theme: "string?" },
    output: { file_path: "string", size_kb: "number", preview_url: "string" },
    ui: [
      "type picker (pptx/docx/xlsx)",
      "WYSIWYG preview",
      "morph timeline (start → end)",
      "equation editor (LaTeX)",
      "live preview pane",
    ],
  },
  {
    id: "media",
    glyph: "🖼",
    name: "media",
    title: "генерация медиа (cloud)",
    model: "flux-2 / veo-3 / lyria-3 · fallback qwen3.8",
    role: "image · video · music, cloud по умолчанию, fallback на local ollama",
    size: "—",
    category: "медиа",
    installed: true,
    backend: "tentacles",
    tools: [
      "mediaImage",
      "mediaVideo",
      "mediaMusic",
      "mediaStatus",
      "mediaListModels",
      "mediaDownloadModel",
    ],
    endpoints: [
      { method: "POST", path: "/api/media/generate", backend: "tentacles", note: "основной submit", stream: true },
      { method: "GET", path: "/api/media/status/<task_id>", backend: "tentacles", note: "polling 2s" },
      { method: "POST", path: "/api/media/cancel/<task_id>", backend: "tentacles", note: "отмена" },
      { method: "GET", path: "/api/media/list?type=", backend: "tentacles", note: "история генераций" },
      { method: "POST", path: "/api/media/download", backend: "tentacles", note: "скачать по URL" },
      { method: "GET", path: "/api/media/models", backend: "tentacles", note: "модели + цены" },
      { method: "GET", path: "/api/media/quota", backend: "tentacles", note: "остаток квоты" },
    ],
    input: {
      type: "image|video|music",
      prompt: "string",
      model: "flux-2|gpt-image-2|ideogram-4|recraft|veo-3|kling|lyria-3|suno-v4",
      size: "1024x1024|1280x720|…",
      aspect_ratio: "1:1|16:9|9:16|4:3|3:2",
      count: "1-4",
      seed: "number?",
    },
    output: {
      images: "[{url,path,size_kb,seed}]",
      task_id: "tsk_… (video/music)",
      status: "queued|processing|done|error",
      cost_usd: "number",
    },
    ui: [
      "вкладки Image / Video / Music",
      "model picker с ☁️/🏠 и ценой",
      "size presets + aspect ratio",
      "count slider, transparent toggle, seed",
      "reference image upload + style strength",
      "video: duration, first/last frame, audio, watermark",
      "music: lyrics, instrumental, genre chips",
      "gallery с download / open in chat / save local",
      "cost counter USD за день",
      "polling 2s + cancel + error display",
    ],
  },
  {
    id: "analyze",
    glyph: "📊",
    name: "analyze",
    title: "анализ данных и файлов",
    model: "qwen3.5:9b vision · qwen2.5vl:32b",
    role: "распознавание изображений/PDF, парсинг CSV/XLSX/JSON, SQL по таблицам, OSINT",
    size: "9.1 ГБ",
    category: "анализ",
    installed: true,
    backend: "tentacles",
    fallback: ["ollama", "proxy"],
    tools: [
      "recognizeImage",
      "recognizePdf",
      "parseCsv",
      "parseXlsx",
      "parseJson",
      "queryTable",
      "searchWeb",
      "getWeather",
      "httpTool",
      "ghosttrackPhone",
      "ghosttrackIP",
      "ghosttrackUsername",
      "ghosttrackEmail",
      "controlHome",
    ],
    endpoints: [
      { method: "POST", path: "/tools/run", backend: "tentacles", note: "универсальный запуск tool", stream: true },
    ],
    input: {
      file_id: "f-abc?",
      url: "https://…?",
      file_path: "/abs/path?",
      query: "string?",
      model: "qwen3.5:9b|qwen2.5vl:32b|qwen3-vl:8b",
    },
    output: {
      description: "string (vision)",
      columns: "[string] (таблицы)",
      rows: "[[...]]",
      confidence: "0-1",
    },
    ui: [
      "drop zone: image / pdf / csv / xlsx / json",
      "вкладки Recognize / Table / Web / OSINT",
      "vision: превью + модель picker",
      "таблица с виртуализацией + SQL-строка (queryTable)",
      "OSINT: phone / ip / username / email",
      "сохранить результат в memory",
    ],
    hotkey: "⌘A",
  },
  {
    id: "generator",
    glyph: "🎨",
    name: "generator",
    title: "генератор контента",
    model: "gemma-4-26b-it · codestral · flux-schnell",
    role: "текст, код, изображения без привязки к специализированному щупальцу",
    size: "26 ГБ",
    category: "медиа",
    installed: true,
    backend: "tentacles",
    fallback: ["mlx", "ollama"],
    tools: ["generateText", "generateImage", "runCode", "imageGenLocal"],
    endpoints: [
      { method: "POST", path: "/tools/run", backend: "tentacles", note: "generateText · SSE tokens", stream: true },
      { method: "POST", path: "/api/diffusers/generate", backend: "tentacles", note: "local image (MFLUX)", stream: true },
    ],
    input: {
      prompt: "string",
      model: "gemma-4-26b-it|qwen3-coder|flux-schnell",
      max_tokens: "2048",
      temperature: "0.7",
      steps: "4",
      width: "1024",
      height: "1024",
      language: "python|js|bash",
    },
    output: {
      text: "string",
      tokens: "number",
      image_path: "string",
      stdout: "string (runCode)",
    },
    ui: [
      "вкладки Text / Image / Code",
      "streaming токенов + счётчик tokens/sec",
      "model picker с 🏠 local / ☁️ cloud",
      "image: steps / size / seed",
      "code: язык + stdout/stderr + exit code",
      "copy / save to memory на каждом результате",
    ],
    hotkey: "⌘G",
  },
  {
    id: "coder",
    glyph: "💻",
    name: "coder",
    title: "программист",
    model: "qwen3-coder · ghidra remote",
    role: "код, sandbox exec, файловые операции, реверс бинарников",
    size: "18 ГБ",
    category: "код",
    installed: true,
    backend: "tentacles",
    fallback: ["proxy"],
    tools: [
      "runCode",
      "listFiles",
      "readFile",
      "writeFile",
      "editFile",
      "statFile",
      "analyzeBinary",
      "extractFirmware",
      "extractStrings",
      "diffBinaries",
      "yaraScan",
      "elfDeepAnalysis",
      "uefiAnalyze",
      "ghidraRemote",
      "riskDashboard",
    ],
    endpoints: [
      { method: "POST", path: "/tools/run", backend: "tentacles", note: "sandbox WORKSPACE_ROOT", stream: true },
    ],
    input: {
      code: "string?",
      language: "python|js|bash|rust|go",
      path: "workspace-relative",
      old_text: "string?",
      new_text: "string?",
      ssh_host: "admin@host.local?",
    },
    output: {
      stdout: "string",
      stderr: "string",
      exit_code: "number",
      task_id: "ghidra_…",
    },
    ui: [
      "file tree (sandbox) слева",
      "редактор + запуск (⌘⏎)",
      "панель stdout/stderr с exit code",
      "вкладка Binary: strings / entropy / ELF / YARA",
      "ghidra remote — статус задачи + логи",
      "risk dashboard: secrets · CVE · crypto score",
    ],
  },
  {
    id: "services",
    glyph: "⚙️",
    name: "services",
    title: "каталог сервисов",
    model: "—",
    role: "self-discover: список щупалец, состояние, версии, эндпоинты",
    size: "—",
    category: "система",
    installed: true,
    backend: "tentacles",
    fallback: ["static-manifest"],
    tools: ["services_list", "services_status", "services_restart", "services_logs"],
    endpoints: [
      { method: "GET", path: "/tools", backend: "tentacles", note: "список сервисов + tools" },
      { method: "GET", path: "/health", backend: "tentacles", note: "health probe" },
    ],
    input: { filter: "online|offline|degraded", include_internal: "bool" },
    output: {
      services: "[{id,name,port,status,uptime_sec,tools_count,version}]",
    },
    ui: [
      "фильтр All / Online / Offline / Degraded",
      "строка сервиса: ● статус · порт · tools_count",
      "uptime · CPU · MEM",
      "кнопки logs / restart / open",
      "auto-refresh каждые 10s",
    ],
    hotkey: "⌘6",
  },
  {
    id: "home",
    glyph: "🏠",
    name: "home",
    title: "стартовый экран",
    model: "—",
    role: "быстрые действия, recent items, подсказки, онбординг",
    size: "—",
    category: "система",
    installed: true,
    backend: "tentacles",
    fallback: ["localStorage"],
    tools: ["getStart", "recentItems", "quickActions", "onboarding"],
    endpoints: [
      { method: "GET", path: "/health", backend: "tentacles", note: "системный статус" },
      { method: "GET", path: "/tools", backend: "tentacles", note: "доступные действия" },
    ],
    input: { user_id: "string?", limit: "10" },
    output: {
      recent_items: "[{type,id,title,ts}]",
      quick_actions: "[{id,icon,label,hotkey}]",
      system_status: "all_green|degraded",
    },
    ui: [
      "приветствие + дата",
      "сетка быстрых действий 3×2 с хоткеями",
      "список «недавнее» (localStorage)",
      "индикатор системного статуса",
      "подсказки / онбординг для новых",
    ],
    hotkey: "⌘0",
  },
];

export const tentacleById = (id: string) => TENTACLES.find((t) => t.id === id) ?? null;
